# 02 Ingestion Test

This notebook is used to test the manual ingestion logic before converting it into an automated Python script.

For each table, the structure should be:

```text
1. Read the CSV file
2. Add metadata columns
3. Load the data into the raw PostgreSQL table
```

## 1. Connect to PostgreSQL

This section imports the required libraries and creates the database connection.

In [9]:
import pandas as pd
from sqlalchemy import create_engine

In [10]:
engine = create_engine(
    "postgresql+psycopg2://postgres:admin123@localhost:5432/hospital_management"
)

## 2. Load patients CSV into the raw table

This cell reads the patients CSV file, adds the `source_file` metadata column, and loads the data into the PostgreSQL table `raw.patients`.

The purpose of this step is to test the ingestion process manually before moving the logic into the automated ingestion script.

In [11]:
df = pd.read_csv("../data/csv_files/1.ingestion/manual-ingestion/patients00.csv")
df.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,Female,04/06/1955,(693)9585183,789 Pine Rd,23/06/2022,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,Female,12/10/1984,8228188767,321 Maple Dr,15/01/2022,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,MALE,21/08/1977,(839)7029847,321 Maple Dr,07/02/2022,PulseSecure,INS650929,LAURA.JONES@MAIL.COM
3,P004,Michael,Johnson,Female,20/02/1981,(901)9443432,123 Elm St,02/03/2021,HealthIndia,INS789944,MICHAEL.JOHNSON@MAIL.COM
4,P005,David,Wilson,Male,23/06/1960,7734463155,123 Elm St,29/09/2021,MedCare Plus,INS788105,DAVID.WILSON@MAIL.COM

In [12]:
df["source_file"] = "patients00.csv"

In [13]:
df.head(2)

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email,source_file
0,P001,David,Williams,Female,04/06/1955,(693)9585183,789 Pine Rd,23/06/2022,WellnessCorp,INS840674,david.williams@mail.com,patients00.csv
1,P002,Emily,Smith,Female,12/10/1984,8228188767,321 Maple Dr,15/01/2022,PulseSecure,INS354079,emily.smith@mail.com,patients00.csv

In [14]:
df.to_sql(
    "patients",
    engine,
    schema="raw",
    if_exists="append",
    index=False
)

35